### PR TITLE
Update website

### LINKED ISSUE #5: Migrate to MDC from MDL
Issue migrated from https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1275

### PR DESCRIPTION
**Pull request by Richienb**
This PR updates the website to use MDC instead of MDL. If you'd like me to continue maintaining this site, feel free to make me a collaborator.

Thank you.

> There seem to be conflicting files. Those files can be removed.

Closes #5. Related to https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1275.

### CODE REVIEW

**Comment by Richienb** [comment]
@Keboo Any update on this?

**Comment by Keboo** [comment]
@Richienb I don't actually have write permissions on this repository. @ButchersBoy can you review?

**Comment by Richienb** [comment]
@ButchersBoy Any update on this?

**Comment by Keboo** [comment]
Closing, there is a new update that is finally coming for this website

**Comment by Richienb** [comment]
no way

**Pull request closed without merging**
